//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTypeApp.TypeRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.web.courses.org/", ConfigurationName="TypeRef.TestService")]
    public interface TestService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.TypeRef.readResponse read(TestTypeApp.TypeRef.read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.readResponse> readAsync(TestTypeApp.TypeRef.read request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.TypeRef.findResponse find(TestTypeApp.TypeRef.find request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.findResponse> findAsync(TestTypeApp.TypeRef.find request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.TypeRef.checkDBResponse checkDB(TestTypeApp.TypeRef.checkDB request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.checkDBResponse> checkDBAsync(TestTypeApp.TypeRef.checkDB request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestTypeApp.TypeRef.saveResponse save(TestTypeApp.TypeRef.save request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.saveResponse> saveAsync(TestTypeApp.TypeRef.save request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestTypeApp.TypeRef.deleteResponse delete(TestTypeApp.TypeRef.delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.deleteResponse> deleteAsync(TestTypeApp.TypeRef.delete request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.TypeRef.readAllResponse readAll(TestTypeApp.TypeRef.readAll request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.readAllResponse> readAllAsync(TestTypeApp.TypeRef.readAll request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.web.courses.org/")]
    public partial class type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="read", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public read() {
        }
        
        public read(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class readResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.TypeRef.type @return;
        
        public readResponse() {
        }
        
        public readResponse(TestTypeApp.TypeRef.type @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="find", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class find {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public find() {
        }
        
        public find(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class findResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.TypeRef.type[] @return;
        
        public findResponse() {
        }
        
        public findResponse(TestTypeApp.TypeRef.type[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkDB", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class checkDB {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public checkDB() {
        }
        
        public checkDB(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkDBResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class checkDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public checkDBResponse() {
        }
        
        public checkDBResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class save {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.TypeRef.type[] arg0;
        
        public save() {
        }
        
        public save(TestTypeApp.TypeRef.type[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class saveResponse {
        
        public saveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public delete() {
        }
        
        public delete(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class deleteResponse {
        
        public deleteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAll", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class readAll {
        
        public readAll() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAllResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class readAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.TypeRef.type[] @return;
        
        public readAllResponse() {
        }
        
        public readAllResponse(TestTypeApp.TypeRef.type[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TestServiceChannel : TestTypeApp.TypeRef.TestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<TestTypeApp.TypeRef.TestService>, TestTypeApp.TypeRef.TestService {
        
        public TestServiceClient() {
        }
        
        public TestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.TypeRef.readResponse TestTypeApp.TypeRef.TestService.read(TestTypeApp.TypeRef.read request) {
            return base.Channel.read(request);
        }
        
        public TestTypeApp.TypeRef.type read(int arg0) {
            TestTypeApp.TypeRef.read inValue = new TestTypeApp.TypeRef.read();
            inValue.arg0 = arg0;
            TestTypeApp.TypeRef.readResponse retVal = ((TestTypeApp.TypeRef.TestService)(this)).read(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.readResponse> TestTypeApp.TypeRef.TestService.readAsync(TestTypeApp.TypeRef.read request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.TypeRef.readResponse> readAsync(int arg0) {
            TestTypeApp.TypeRef.read inValue = new TestTypeApp.TypeRef.read();
            inValue.arg0 = arg0;
            return ((TestTypeApp.TypeRef.TestService)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.TypeRef.findResponse TestTypeApp.TypeRef.TestService.find(TestTypeApp.TypeRef.find request) {
            return base.Channel.find(request);
        }
        
        public TestTypeApp.TypeRef.type[] find(string arg0) {
            TestTypeApp.TypeRef.find inValue = new TestTypeApp.TypeRef.find();
            inValue.arg0 = arg0;
            TestTypeApp.TypeRef.findResponse retVal = ((TestTypeApp.TypeRef.TestService)(this)).find(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.findResponse> TestTypeApp.TypeRef.TestService.findAsync(TestTypeApp.TypeRef.find request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.TypeRef.findResponse> findAsync(string arg0) {
            TestTypeApp.TypeRef.find inValue = new TestTypeApp.TypeRef.find();
            inValue.arg0 = arg0;
            return ((TestTypeApp.TypeRef.TestService)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.TypeRef.checkDBResponse TestTypeApp.TypeRef.TestService.checkDB(TestTypeApp.TypeRef.checkDB request) {
            return base.Channel.checkDB(request);
        }
        
        public bool checkDB(string arg0) {
            TestTypeApp.TypeRef.checkDB inValue = new TestTypeApp.TypeRef.checkDB();
            inValue.arg0 = arg0;
            TestTypeApp.TypeRef.checkDBResponse retVal = ((TestTypeApp.TypeRef.TestService)(this)).checkDB(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.checkDBResponse> TestTypeApp.TypeRef.TestService.checkDBAsync(TestTypeApp.TypeRef.checkDB request) {
            return base.Channel.checkDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.TypeRef.checkDBResponse> checkDBAsync(string arg0) {
            TestTypeApp.TypeRef.checkDB inValue = new TestTypeApp.TypeRef.checkDB();
            inValue.arg0 = arg0;
            return ((TestTypeApp.TypeRef.TestService)(this)).checkDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.TypeRef.saveResponse TestTypeApp.TypeRef.TestService.save(TestTypeApp.TypeRef.save request) {
            return base.Channel.save(request);
        }
        
        public void save(TestTypeApp.TypeRef.type[] arg0) {
            TestTypeApp.TypeRef.save inValue = new TestTypeApp.TypeRef.save();
            inValue.arg0 = arg0;
            TestTypeApp.TypeRef.saveResponse retVal = ((TestTypeApp.TypeRef.TestService)(this)).save(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.saveResponse> TestTypeApp.TypeRef.TestService.saveAsync(TestTypeApp.TypeRef.save request) {
            return base.Channel.saveAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.TypeRef.saveResponse> saveAsync(TestTypeApp.TypeRef.type[] arg0) {
            TestTypeApp.TypeRef.save inValue = new TestTypeApp.TypeRef.save();
            inValue.arg0 = arg0;
            return ((TestTypeApp.TypeRef.TestService)(this)).saveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.TypeRef.deleteResponse TestTypeApp.TypeRef.TestService.delete(TestTypeApp.TypeRef.delete request) {
            return base.Channel.delete(request);
        }
        
        public void delete(int arg0) {
            TestTypeApp.TypeRef.delete inValue = new TestTypeApp.TypeRef.delete();
            inValue.arg0 = arg0;
            TestTypeApp.TypeRef.deleteResponse retVal = ((TestTypeApp.TypeRef.TestService)(this)).delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.deleteResponse> TestTypeApp.TypeRef.TestService.deleteAsync(TestTypeApp.TypeRef.delete request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.TypeRef.deleteResponse> deleteAsync(int arg0) {
            TestTypeApp.TypeRef.delete inValue = new TestTypeApp.TypeRef.delete();
            inValue.arg0 = arg0;
            return ((TestTypeApp.TypeRef.TestService)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.TypeRef.readAllResponse TestTypeApp.TypeRef.TestService.readAll(TestTypeApp.TypeRef.readAll request) {
            return base.Channel.readAll(request);
        }
        
        public TestTypeApp.TypeRef.type[] readAll() {
            TestTypeApp.TypeRef.readAll inValue = new TestTypeApp.TypeRef.readAll();
            TestTypeApp.TypeRef.readAllResponse retVal = ((TestTypeApp.TypeRef.TestService)(this)).readAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.TypeRef.readAllResponse> TestTypeApp.TypeRef.TestService.readAllAsync(TestTypeApp.TypeRef.readAll request) {
            return base.Channel.readAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.TypeRef.readAllResponse> readAllAsync() {
            TestTypeApp.TypeRef.readAll inValue = new TestTypeApp.TypeRef.readAll();
            return ((TestTypeApp.TypeRef.TestService)(this)).readAllAsync(inValue);
        }
    }
}
