//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTypeApp.ManufactureRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.web.courses.org/", ConfigurationName="ManufactureRef.ManufactureService")]
    public interface ManufactureService {
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.ManufactureRef.readResponse read(TestTypeApp.ManufactureRef.read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.readResponse> readAsync(TestTypeApp.ManufactureRef.read request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.ManufactureRef.findResponse find(TestTypeApp.ManufactureRef.find request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.findResponse> findAsync(TestTypeApp.ManufactureRef.find request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.ManufactureRef.checkDBResponse checkDB(TestTypeApp.ManufactureRef.checkDB request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.checkDBResponse> checkDBAsync(TestTypeApp.ManufactureRef.checkDB request);
        
        // CODEGEN: Параметр "arg0" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestTypeApp.ManufactureRef.saveResponse save(TestTypeApp.ManufactureRef.save request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.saveResponse> saveAsync(TestTypeApp.ManufactureRef.save request);
        
        // CODEGEN: Параметр "arg0" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestTypeApp.ManufactureRef.deleteResponse delete(TestTypeApp.ManufactureRef.delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.deleteResponse> deleteAsync(TestTypeApp.ManufactureRef.delete request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestTypeApp.ManufactureRef.readAllResponse readAll(TestTypeApp.ManufactureRef.readAll request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.readAllResponse> readAllAsync(TestTypeApp.ManufactureRef.readAll request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.web.courses.org/")]
    public partial class manufacture : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="read", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public read() {
        }
        
        public read(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class readResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.ManufactureRef.manufacture @return;
        
        public readResponse() {
        }
        
        public readResponse(TestTypeApp.ManufactureRef.manufacture @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="find", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class find {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public find() {
        }
        
        public find(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class findResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.ManufactureRef.manufacture[] @return;
        
        public findResponse() {
        }
        
        public findResponse(TestTypeApp.ManufactureRef.manufacture[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkDB", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class checkDB {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public checkDB() {
        }
        
        public checkDB(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkDBResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class checkDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public checkDBResponse() {
        }
        
        public checkDBResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class save {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.ManufactureRef.manufacture[] arg0;
        
        public save() {
        }
        
        public save(TestTypeApp.ManufactureRef.manufacture[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class saveResponse {
        
        public saveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public delete() {
        }
        
        public delete(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class deleteResponse {
        
        public deleteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAll", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class readAll {
        
        public readAll() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAllResponse", WrapperNamespace="http://soap.web.courses.org/", IsWrapped=true)]
    public partial class readAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.web.courses.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestTypeApp.ManufactureRef.manufacture[] @return;
        
        public readAllResponse() {
        }
        
        public readAllResponse(TestTypeApp.ManufactureRef.manufacture[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManufactureServiceChannel : TestTypeApp.ManufactureRef.ManufactureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManufactureServiceClient : System.ServiceModel.ClientBase<TestTypeApp.ManufactureRef.ManufactureService>, TestTypeApp.ManufactureRef.ManufactureService {
        
        public ManufactureServiceClient() {
        }
        
        public ManufactureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManufactureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufactureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufactureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.ManufactureRef.readResponse TestTypeApp.ManufactureRef.ManufactureService.read(TestTypeApp.ManufactureRef.read request) {
            return base.Channel.read(request);
        }
        
        public TestTypeApp.ManufactureRef.manufacture read(int arg0) {
            TestTypeApp.ManufactureRef.read inValue = new TestTypeApp.ManufactureRef.read();
            inValue.arg0 = arg0;
            TestTypeApp.ManufactureRef.readResponse retVal = ((TestTypeApp.ManufactureRef.ManufactureService)(this)).read(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.readResponse> TestTypeApp.ManufactureRef.ManufactureService.readAsync(TestTypeApp.ManufactureRef.read request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.readResponse> readAsync(int arg0) {
            TestTypeApp.ManufactureRef.read inValue = new TestTypeApp.ManufactureRef.read();
            inValue.arg0 = arg0;
            return ((TestTypeApp.ManufactureRef.ManufactureService)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.ManufactureRef.findResponse TestTypeApp.ManufactureRef.ManufactureService.find(TestTypeApp.ManufactureRef.find request) {
            return base.Channel.find(request);
        }
        
        public TestTypeApp.ManufactureRef.manufacture[] find(string arg0) {
            TestTypeApp.ManufactureRef.find inValue = new TestTypeApp.ManufactureRef.find();
            inValue.arg0 = arg0;
            TestTypeApp.ManufactureRef.findResponse retVal = ((TestTypeApp.ManufactureRef.ManufactureService)(this)).find(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.findResponse> TestTypeApp.ManufactureRef.ManufactureService.findAsync(TestTypeApp.ManufactureRef.find request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.findResponse> findAsync(string arg0) {
            TestTypeApp.ManufactureRef.find inValue = new TestTypeApp.ManufactureRef.find();
            inValue.arg0 = arg0;
            return ((TestTypeApp.ManufactureRef.ManufactureService)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.ManufactureRef.checkDBResponse TestTypeApp.ManufactureRef.ManufactureService.checkDB(TestTypeApp.ManufactureRef.checkDB request) {
            return base.Channel.checkDB(request);
        }
        
        public bool checkDB(string arg0) {
            TestTypeApp.ManufactureRef.checkDB inValue = new TestTypeApp.ManufactureRef.checkDB();
            inValue.arg0 = arg0;
            TestTypeApp.ManufactureRef.checkDBResponse retVal = ((TestTypeApp.ManufactureRef.ManufactureService)(this)).checkDB(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.checkDBResponse> TestTypeApp.ManufactureRef.ManufactureService.checkDBAsync(TestTypeApp.ManufactureRef.checkDB request) {
            return base.Channel.checkDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.checkDBResponse> checkDBAsync(string arg0) {
            TestTypeApp.ManufactureRef.checkDB inValue = new TestTypeApp.ManufactureRef.checkDB();
            inValue.arg0 = arg0;
            return ((TestTypeApp.ManufactureRef.ManufactureService)(this)).checkDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.ManufactureRef.saveResponse TestTypeApp.ManufactureRef.ManufactureService.save(TestTypeApp.ManufactureRef.save request) {
            return base.Channel.save(request);
        }
        
        public void save(TestTypeApp.ManufactureRef.manufacture[] arg0) {
            TestTypeApp.ManufactureRef.save inValue = new TestTypeApp.ManufactureRef.save();
            inValue.arg0 = arg0;
            TestTypeApp.ManufactureRef.saveResponse retVal = ((TestTypeApp.ManufactureRef.ManufactureService)(this)).save(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.saveResponse> TestTypeApp.ManufactureRef.ManufactureService.saveAsync(TestTypeApp.ManufactureRef.save request) {
            return base.Channel.saveAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.saveResponse> saveAsync(TestTypeApp.ManufactureRef.manufacture[] arg0) {
            TestTypeApp.ManufactureRef.save inValue = new TestTypeApp.ManufactureRef.save();
            inValue.arg0 = arg0;
            return ((TestTypeApp.ManufactureRef.ManufactureService)(this)).saveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.ManufactureRef.deleteResponse TestTypeApp.ManufactureRef.ManufactureService.delete(TestTypeApp.ManufactureRef.delete request) {
            return base.Channel.delete(request);
        }
        
        public void delete(int arg0) {
            TestTypeApp.ManufactureRef.delete inValue = new TestTypeApp.ManufactureRef.delete();
            inValue.arg0 = arg0;
            TestTypeApp.ManufactureRef.deleteResponse retVal = ((TestTypeApp.ManufactureRef.ManufactureService)(this)).delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.deleteResponse> TestTypeApp.ManufactureRef.ManufactureService.deleteAsync(TestTypeApp.ManufactureRef.delete request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.deleteResponse> deleteAsync(int arg0) {
            TestTypeApp.ManufactureRef.delete inValue = new TestTypeApp.ManufactureRef.delete();
            inValue.arg0 = arg0;
            return ((TestTypeApp.ManufactureRef.ManufactureService)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestTypeApp.ManufactureRef.readAllResponse TestTypeApp.ManufactureRef.ManufactureService.readAll(TestTypeApp.ManufactureRef.readAll request) {
            return base.Channel.readAll(request);
        }
        
        public TestTypeApp.ManufactureRef.manufacture[] readAll() {
            TestTypeApp.ManufactureRef.readAll inValue = new TestTypeApp.ManufactureRef.readAll();
            TestTypeApp.ManufactureRef.readAllResponse retVal = ((TestTypeApp.ManufactureRef.ManufactureService)(this)).readAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.readAllResponse> TestTypeApp.ManufactureRef.ManufactureService.readAllAsync(TestTypeApp.ManufactureRef.readAll request) {
            return base.Channel.readAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestTypeApp.ManufactureRef.readAllResponse> readAllAsync() {
            TestTypeApp.ManufactureRef.readAll inValue = new TestTypeApp.ManufactureRef.readAll();
            return ((TestTypeApp.ManufactureRef.ManufactureService)(this)).readAllAsync(inValue);
        }
    }
}
